### ISSUE TITLE
Workbench unusable in FC 0.19 due to changed Python functions

### ISSUE THREAD

**Issue by donovaly** [JMG1/ExplodedAssembly#17]
- use the menu to load the example file

result: you get this warning: "Enumeration index -1 is out of range, ignore it"

- let's ignore this and move on by pressing the button "Create Bolt Group"

result: `<Part> ViewProviderExt.cpp(1325): Cannot compute Inventor representation for the shape of example#trajectory_line021
<Part> ViewProviderExt.cpp(1325): Cannot compute Inventor representation for the shape of example#trajectory_line021
264.696 <App> Document.cpp(3462): Failed to recompute example#Pocket005: No object linked
Recompute failed! Please check report view.`

This might come because of the new link feature of FC. If so, I can bring this issue to the FC forum.

- now select 2 edges of your choice and press the button "Create Simple Group"

result: you get this error: `Running the Python command 'CreateSimpleGroup' failed:
Traceback (most recent call last):
  File "C:\Users\stoehr\AppData\Roaming\FreeCAD\Mod\ExplodedAssembly\EAInit.py", line 71, in Activated
    ea.createSimpleDisassemble()
  File "C:\Users\stoehr\AppData\Roaming\FreeCAD\Mod\ExplodedAssembly\ExplodedAssembly.py", line 213, in createSimpleDisassemble
    dir_vector = selection[-1].SubObjects[-1].normalAt(0, 0)
function takes exactly 1 argument (2 given)`

It seems the FC python functions have changed and ExplodedAssembly must be adapted accordingly.

**Comment by hkienle** [comment]
Are there any plans to support 0.19?

**Comment by donovaly** [comment]
It seems this workbench is orphaned. However, the assembly workbenches A2plus and Assembly4 supports now already some animations. Nevertheless a real explode workbench would be very valuable.

**Comment by hkienle** [comment]
Thanks for the pointers!

**Comment by ThomasEgi** [comment]
After Installing A2plus and Assembly4 I got the EA workbench to move objects around (strange enough). Either it is related to some module provided externally or I was simply selecting the wrong things before (as I had never used the EA Workbench before).
