### ISSUE TITLE
Explode Assembly seems to be broken?

### ISSUE THREAD

**Issue by 0x007E** [JMG1/ExplodedAssembly#36]
Currently for me it is not possible to explode drawings with Freecad 20.1 (Win). If i use an older Version of ExplodeAssembly there are no problems. The following error message appears:

```
09:35:08  Exploded Assembly workbench loaded
09:35:10  Running the Python command 'GoToEnd' failed:
Traceback (most recent call last):
  File "C:\Users\ragae\AppData\Roaming\FreeCAD\Mod\ExplodedAssembly\EAInit.py", line 315, in Activated
    ea.goToEnd()
  File "C:\Users\ragae\AppData\Roaming\FreeCAD\Mod\ExplodedAssembly\ExplodedAssembly.py", line 450, in goToEnd
    obj_base = traj.dir_vectors[n]*inc_D

can't multiply sequence by non-int of type 'float'
```
Maybe it is due the setup of `AnimationStepTime`?
![image](https://github.com/JMG1/ExplodedAssembly/assets/61001336/92a1eca6-9482-488a-88f5-0a9199eba2fd)

I didn´t test if the problems are comming from there but if the code was changed to only accept int it would be necessary to change all my project. I haven´t checked the code of the last update but possible this is a  #bug?

**Comment by s-light** [comment]
https://github.com/JMG1/ExplodedAssembly/blame/master/ExplodedAssembly.py#L450
At least ther was sonething chabged exactky in this line...

**Comment by JMG1** [comment]
I am not able to reproduce, could you post a file with the issue at the FreeCAD forum?

**Comment by 0x007E** [comment]
@JMG1 -> You can use the mechanical.FCStd template from [this](https://github.com/0x007E/freecad) repository. Message is still the same:

```
09:27:33  Exploded Assembly workbench loaded
09:27:37  Running the Python command 'GoToEnd' failed:
Traceback (most recent call last):
  File "C:\Users\***\AppData\Roaming\FreeCAD\Mod\ExplodedAssembly\EAInit.py", line 315, in Activated
    ea.goToEnd()
  File "C:\Users\***\AppData\Roaming\FreeCAD\Mod\ExplodedAssembly\ExplodedAssembly.py", line 450, in goToEnd
    obj_base = traj.dir_vectors[n]*inc_D

can't multiply sequence by non-int of type 'float'
```
## FreeCAD Version:
```
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Austria (de_AT)
Installed mods: 
  * ExplodedAssembly
  * fasteners 0.5.12
  * kicadStepUpMod 10.23.2
  * ThreadProfile 1.89.0
[/code]
```

## Installed version of ExplodeAssembly

```
Unknown -> Installed. This is the latest version available for branch master.
```

> With another computer, where the same version of `FreeCAD` is installed but an older version of `ExplodeAssembly` it is no problem and everything is working as expected.
