### ISSUE TITLE
Is ExplodedAssembly ready for FreeCAD 1.0 Release ?

### ISSUE THREAD

**Issue by luzpaz** [JMG1/ExplodedAssembly#41]
* https://github.com/FreeCAD/Addons/issues/13

**Comment by obones** [comment]
FWIW, I installed it in 1.0.2 just now and while it is possible to select that workbench, any attempt to animate a body or part gives this error:

```
Running the Python command 'CreateSimpleGroup' failed:
Traceback (most recent call last):
  File "C:\Users\obones\AppData\Roaming\FreeCAD\Mod\ExplodedAssembly\EAInit.py", line 71, in Activated
    ea.createSimpleDisassemble()
  File "C:\Users\obones\AppData\Roaming\FreeCAD\Mod\ExplodedAssembly\ExplodedAssembly.py", line 208, in createSimpleDisassemble
    dir_vector = selection[-1].SubObjects[-1].normalAt(0, 0)
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^

tuple index out of range
```

Not sure what to do with that.
